### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [AxelRocha/DesafioTunts#2]
Hi,<br><br>url : https://github.com/AxelRocha/DesafioTunts/blob/2280cf724ac7adcbf95553174176372d697eeac5/src/main/resources/credentials.json <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by AxelRocha** [comment]
Hi @shaybenb,

I appreciate your worry. I do know the problems of what I did.

The purpose of this project kinda alows me to do it. Its a test for a intership, some people will run and evaluate it, so I choosed to leave this file there, with the api credentials, so they don't need to do anything other than download and run the project.

Thank you.
